---
- name: "IP Filter test"
  hosts: 192.168.30.130
  gather_facts: false

  tasks:
    - name: "IP Address Filter stuff"
      vars:
        myip: "192.168.30.1/24"
      debug:
        msg: "{{ myip | ipaddr('network') }}"

