---

- name: "Filter Test"
  hosts: "192.168.30.130"
  tasks:
    - name: "Testing some filters Stuff"
      vars:
         mylist:
          - 5
          - 10
          - 4
          - 44
          - 21
      debug:
        msg: "{{ mylist | min }}"   
